# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Rafael León Estrada
title: Computer Engineering Student
email: rle16@hotmail.com
phone number: 3323403259
website: https://github.com/skillerhero

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  skillerhero
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: skillerhero
linkedin_username: skillerhero
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: channel/UCio8YZPyLAtfjVfCK6C5ooA
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: https://www.youtube.com/channel/UCio8YZPyLAtfjVfCK6C5ooA
  url: https://www.youtube.com/channel/UCio8YZPyLAtfjVfCK6C5ooA
  icon: fab fa-brands fa-youtube
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Rafael and I'm a junior software developer.

  I am most skilled in: <mark>C#</mark> and <mark>MySQL</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Restaurant reservation system
        #link: https://github.com/skillerhero/Missushi
        # link_text: Project Website
        additional_links:
          - title:  Github repository
            icon: fab fa-github
            url: https://github.com/skillerhero/Missushi
          - title:  YouTube video
            icon: fab fa-youtube
            url: https://youtu.be/KTdBXzdd9pk
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Restaurant reservation system project.
        description: | # this will include new lines to allow paragraphs
          I made this project in order to pass a school subject. I believe it's a decent project and I could experiment a little with amazon web services, C# and MySQL. 
      - layout: top-middle
        title: School material app
        #link: https://github.com/skillerhero/Missushi
        # link_text: Project Website
        additional_links:
          - title:  Github repository
            icon: fab fa-github
            url: https://github.com/rafamiguel/read-watch
          - title:  YouTube video
            icon: fab fa-youtube
            url: https://youtu.be/Nupxc5eq0yA
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
       # quote: >
          #Restaurant reservation system project.
        description: | # this will include new lines to allow paragraphs
          A classmate and I developed and documented an Android app called Read and Watch which was intended to help high school students with some of their subjects providing useful documents and videos. It was made in Java for Android, using PHP for queries and MySQL as the  main database and Firebase as an auxiliary database. 


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ISTRA
        link: https://istra.com.mx/
        # link_text: boringcompany.com
        sub_title: Fullstack developer
        caption: January 2022 - Present
        quote: >
          We are constantly developing technological solutions that allow our clients to better manage their car insurance and make quicker decisions that allow them to make their own businesses more profitable.
        description: | # this will include new lines to allow paragraphs
          I usually work with ASP (vb.net), C# and SQL server.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Centro de Enseñanza Técnica Industrial Plantel Colomos
        caption: Feb 2016 - Dec 2019
        sub_title: Software Development Technician
        #quote: >
        description: | # this will include new lines to allow paragraphs
          During my time at CETI I got the foundation of my technical knowledge. I would say that I became a hard worker during my stay at CETI.
      - layout: left
        title: Centro Universitario de Ciencias Exactas e Ingenierías
        caption: Jan 2020 - Jun 2024
        sub_title: Computer Engineer
        #quote: >
          #Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | 
          Currently trying to figure out what I'm passionate about regarding computer science. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in computer engineering some of my other interests and hobbies are:
      - Gaming
      - Listening to rock music
      - Watching series
      - Learning to play violin

    #Look at this cool image  
    #![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
references_title: Zapopan, Jal.

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
